### ISSUE TITLE
GeneOntologyDataset error

### ISSUE THREAD

**Issue by cgoliver** [BorgwardtLab/proteinshake#180]
Fresh install from master branch

```
>>> from proteinshake.datasets import GeneOntologyDataset
>>> proteins = GeneOntologyDataset(root="./data").to_graph(k=5).pyg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cgonzalez/Projects/proteinshake/proteinshake/datasets/gene_ontology.py", line 17, in __init__
    self.godag = GODag(f'{self.root}/go-basic.obo', prt=None)
  File "/Users/cgonzalez/Projects/proteinshake/.venv/lib/python3.10/site-packages/goatools/obo_parser.py", line 321, in __init__
    self.version, self.data_version = self.load_obo_file(
  File "/Users/cgonzalez/Projects/proteinshake/.venv/lib/python3.10/site-packages/goatools/obo_parser.py", line 327, in load_obo_file
    reader = OBOReader(obo_file, optional_attrs)
  File "/Users/cgonzalez/Projects/proteinshake/.venv/lib/python3.10/site-packages/goatools/obo_parser.py", line 56, in __init__
    raise Exception(
Exception: COULD NOT READ(./data/go-basic.obo)
download obo file first
 [http://geneontology.org/ontology/go-basic.obo]
```

**Comment by timkucera** [comment]
should be fixed with the new release
